### ISSUE TITLE
module in browser

### ISSUE THREAD

**Issue by M7Mansour** [GSG-G11/OGANI-ecommerce-app-t3#40]
https://github.com/GSG-G11/OGANI-ecommerce-app-t3/blob/a19a31788882faa8c634e46a23b068af6be48a34/js/logic.js#L34
the browser doesn't recognize the module object so we don't use it in the scripts that run in the browser.
I can't see why you used it in here. 
but if your purpose is to export the variables into other scripts you can include the script file that include these variables in the HTML page above the other script file that will use the varialbes.

**Comment by haniolwan** [comment]
whats the solution? we used module to export functions so we can call them in other js files..
